---

janus_admin_secret: secret
dd_api_key: datadog_api_key
collect_ec2_tags: "no"
coturn_realm: "hubs"
coturn_listening_ip: "127.0.0.1"
coturn_external_ip: "127.0.0.1"
coturn_relay_ip: "127.0.0.1"
coturn_tls_listening_port: 5349
coturn_no_udp: "true"
coturn_no_tcp: "true"
coturn_no_dtls: "true"
coturn_min_port: 49152
coturn_max_port: 51609
coturn_psql_userdb: "postgresql://postgres:postgres@localhost/ret_dev"
