---

ret_db_hostname: "hubs.local"
ret_db_username: "postgres"
ret_db_password: "postgres"
ret_db_database: "ret_production"
phoenix_url_host: "hubs.local"
phoenix_url_port: 4000
phoenix_static_url_host: "hubs.local"
phoenix_static_url_port: 4000
phoenix_cors_proxy_url_host: "hubs-proxy.com"
phoenix_allow_all_origins: "true"
hubs_page_origin: "https://hubs.local:8080"
spoke_page_origin: "https://hubs.local:9090"
admin_page_origin: "https://hubs.local:8181"
page_origin_insecure_ssl: "true"
ret_bot_access_key: "secret"
giphy_api_key: null
deviantart_client_id: null
deviantart_client_secret: null
imgur_mashape_api_key: null
imgur_client_id:  null
tenor_api_key: null
bing_search_api_key: null
twitch_client_id: null
ytdl_host: "https://hubs.local:8081"
google_poly_api_key: null
youtube_api_key: null
sketchfab_api_key: null
photomnemonic_endpoint: "https://pyrkq22jjj.execute-api.us-west-1.amazonaws.com/public"
discord_client_client_id: null
discord_client_client_secret: null
discord_client_bot_token: null
uploads_host: "https://hubs.local:4000"
content_security_policy: "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline' blob: data:; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline'; worker-src * 'self' blob:;"
mailer_server: null
mailer_port: "23"
mailer_username: null
mailer_password: null
mailer_from: null
guardian_secret_key: "47iqPEdWcfE7xRnyaxKDLt9OGEtkQG3SycHBEMOuT2qARmoESnhc76IgCUjaQIwX"
guardian_perms_key: null
guardian_oauth_token_key: null
support_slack_webhook_url: null
web_push_subject: "mailto:admin@hubs.local"
web_push_public_key: "BAb03820kHYuqIvtP6QuCKZRshvv_zp5eDtqkuwCUAxASBZMQbFZXzv8kjYOuLGF16A3k8qYnIN10_4asB-Aw7w"
web_push_private_key: "w76tXh1d3RBdVQ5eINevXRwW6Ow6uRcBa8tBDOXfmxM"
sentry_dsn: null
janus_admin_secret: "secret"
erlang_node_cookie: "4hLcgv+k1GO+fgV43dJ+LHkmFRoCqdxyo/xV93MFVff9XF0+sTR4OAQydT3fxBtD"
phoenix_secret_key: "5sB9mzMMgLdsQZoPF6qOPP1x5PNxlzXi+xbP8Zvqgw2aAz0xlw6qIZjWrCduqORa"
phoenix_admin_access_key: "admin"
phoenix_port: 4000
run_hostname_dns_suffix: ""
alb_target_group_arn: ""
smoke_alb_target_group_arn: ""
uploads_storage_path: "/hab/svc/reticulum/var"
uploads_ttl: 172800
janus_admin_port: 7000
janus_service_name: "janus-gateway"
cors_origins: "*"
dd_api_key: null
ret_db_ssl: "true"
insecure_ssl: "true"
